name: mf-mono Build
on:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: yarn install
      - run: yarn test
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-${{ github.sha }}
          path: ./coverage
