name: mf-mono Build
on:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: yarn install
      - run: yarn test
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report-${{ github.sha }}
          path: ./coverage
      - name: Report test coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: javascript
          coverage-file: coverage-temp/coverage-final.json
          dsn: ${{ secrets.DEEPSOURCE_TOKEN }}
  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: mf-mono
          persist-credentials: false
      - uses: actions/download-artifact@v3
        with:
          name: coverage-report-${{ github.sha }}
          path: mf-mono/coverage-report-${{ github.sha }}
      - name: publish
        working-directory: mf-mono/
        run: |
          ls -lrt
          git config user.name ${{ secrets.USERNAME }}
          git config user.email ${{ secrets.EMAIL }}
          git add .
          git commit -m "upload coverage report"
          git push 'https://${{ secrets.USERNAME }}:${{ secrets.PAT }}@github.com/N0-man/mf-mono.git' gh-pages
      - run: echo "Coverage Reprot https://n0-man.github.io/mf-mono/coverage-report-${{ github.sha }}"
